# Generated by Django 3.2.5 on 2021-07-21 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='tabel_num',
            field=models.IntegerField(default=0, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 12, 33, 53, 884414), verbose_name='Время публикации'),
        ),
    ]
