# Generated by Django 3.2.5 on 2021-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0002_alter_userstatistic_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='loc_class',
            field=models.CharField(choices=[('badge badge-pill badge-primary', 'Синий'), ('badge badge-pill badge-secondary', 'Серый'), ('badge badge-pill badge-success', 'зеленый'), ('badge badge-pill badge-info', 'голубой'), ('badge badge-pill badge-warning', 'желтый'), ('badge badge-pill badge-danger', 'красный'), ('badge badge-pill badge-light', 'светлый'), ('badge badge-pill badge-dark', 'темный')], max_length=200, verbose_name='Класс bootstrap'),
        ),
    ]
