# Generated by Django 3.2.5 on 2021-07-21 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0002_auto_20210721_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='loc_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание местоположение'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 13, 11, 41, 91091), verbose_name='Время публикации'),
        ),
    ]
