# Generated by Django 3.2.5 on 2021-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0003_auto_20210722_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='loc_class',
            field=models.CharField(choices=[('синий', 'badge badge-pill badge-primary'), ('серый', 'badge badge-pill badge-secondary'), ('зеленый', 'badge badge-pill badge-success'), ('голубой', 'badge badge-pill badge-info'), ('желтый', 'badge badge-pill badge-warning'), ('красный', 'badge badge-pill badge-danger'), ('светлый', 'badge badge-pill badge-light'), ('темный', 'badge badge-pill badge-dark')], default='синий', max_length=200, verbose_name='Класс bootstrap'),
        ),
    ]
