# Generated by Django 3.2.5 on 2021-07-21 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0004_auto_20210721_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 13, 28, 21, 35285), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 13, 28, 21, 35285), verbose_name='Время публикации'),
        ),
    ]
