# Generated by Django 3.2.5 on 2021-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0004_alter_userlocation_loc_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='loc_class',
            field=models.CharField(choices=[('badge badge-pill badge-primary', 'синий'), ('badge badge-pill badge-secondary', 'серый'), ('badge badge-pill badge-success', 'зеленый'), ('badge badge-pill badge-info', 'голубой'), ('badge badge-pill badge-warning', 'желтый'), ('badge badge-pill badge-danger', 'красный'), ('badge badge-pill badge-light', 'светлый'), ('badge badge-pill badge-dark', 'темный')], default='badge badge-pill badge-primary', max_length=200, verbose_name='Класс bootstrap'),
        ),
    ]
