# Generated by Django 3.2.5 on 2021-07-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0006_alter_userlocation_loc_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistic_app.profile', verbose_name='Пользователь'),
        ),
    ]
