# Generated by Django 3.2.5 on 2021-07-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0007_alter_userstatistic_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Время публикации'),
        ),
    ]
