# Generated by Django 3.2.5 on 2021-07-21 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0010_auto_20210721_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 13, 37, 39, 669237), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 13, 37, 39, 670237), verbose_name='Время публикации'),
        ),
    ]
