# Generated by Django 3.2.5 on 2021-07-21 10:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0012_auto_20210721_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 13, 40, 17, 843284), verbose_name='Время публикации'),
        ),
    ]
