# Generated by Django 3.2.5 on 2021-08-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0014_remove_profile_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistic_app.userlocation', verbose_name='Местоположение пользователя'),
        ),
    ]
