# Generated by Django 3.2.5 on 2021-09-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0018_alter_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentproject',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
