# Generated by Django 3.2.5 on 2021-09-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0020_agentproject_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproject',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='agentproject',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='объекты', to='statistic_app.Project', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='agentproject',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
    ]
