# Generated by Django 3.2.5 on 2021-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0021_auto_20210922_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('badge bg-danger', 'Не начат'), ('badge bg-secondary', 'Подготовка'), ('badge bg-primary', 'В работе'), ('badge bg-success', 'Сдан'), ('badge bg-warning text-dark', 'Тех. обслуживание')], default='Не начат', max_length=200, verbose_name='Статус проекта'),
        ),
    ]
