# Generated by Django 3.2.5 on 2021-09-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0023_auto_20210922_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status_style',
        ),
    ]
