# Generated by Django 3.2.5 on 2021-09-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0026_auto_20210923_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='statistic_app.project', verbose_name='Проект'),
        ),
    ]
