# Generated by Django 3.2.5 on 2021-09-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0027_alter_userstatistic_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон(ы)'),
        ),
    ]
