# Generated by Django 3.2.5 on 2021-09-24 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0029_profile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproject',
            name='organisation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Время события'),
        ),
    ]
