# Generated by Django 3.2.5 on 2021-09-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0032_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
